### ISSUE TITLE
make angular2gridster AOT compatible

### ISSUE THREAD

**Issue by rajesh-kanakabandi** [swiety85/angular2gridster#10]
@getsales-damian @michalstepien @swiety85 
when using in a project with angular-cli. build fails cause angular2gridster is not AOT compatible.

`ERROR in Error encountered resolving symbol values statically. Calling function 'makeDecorator', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol NgModule in /home/userx/angular2_app/node_modules/angular2gridster/node_modules/@angular/core/src/metadata/ng_module.d.ts, resolving symbol NgModule in /home/userx/angular2_app/node_modules/angular2gridster/node_modules/@angular/core/src/metadata.d.ts, resolving symbol NgModule in /home/userx/angular2_app/node_modules/angular2gridster/node_modules/@angular/core/src/core.d.ts, resolving symbol NgModule in /home/userx/angular2_app/node_modules/angular2gridster/node_modules/@angular/core/index.d.ts, resolving symbol GridsterModule in /home/userx/angular2_app/node_modules/angular2gridster/src/gridster.module.ts, resolving symbol GridsterModule in /home/userx/angular2_app/node_modules/angular2gridster/src/gridster.module.ts`

is there a way to get around this for the time being?

https://medium.com/@isaacplmann/making-your-angular-2-library-statically-analyzable-for-aot-e1c6f3ebedd5#.vlam4896g

**Comment by swiety85** [comment]
We will check and fix it as soon as possible.
I can only say that with angular-cli@1.0.0-beta.25.5 it works ok. As temporary solution I can only suggest to downgrade to given version of angular-cli.
Thank you for information.

**Comment by rajesh-kanakabandi** [comment]
downgrading to angular-cli@1.0.0-beta.25.5 did not help. I still get the same error. 

here is a list of angular-cli versions that i used:
angular-cli@1.0.0-beta.26 (original state),
downgraded to angular-cli@1.0.0-beta.25.5 (still same error)
upgraded to angular-cli@latest (error continues).

to isolate the cause of error, Ii commented out the GridsterModule import and the build was successful.

**Comment by swiety85** [comment]
Should work now in v. 0.4.0.

**Comment by dedalusmax** [comment]
it still doesn't work for me. i'm using webpack, and have downloaded 0.4.0 and in the vendor.js file i have the following:

import 'angular2gridster';

that should suffice the webpack, IMHO, but it doesn't seem to work.

**Comment by swiety85** [comment]
Ive checked that with newest angular-cli and it works. Does your issue relates to @rajesh-kanakabandi ?

**Comment by michalstepien** [comment]
I checked in newest cli and it works.
