### ISSUE TITLE
Dynamic change position

### ISSUE THREAD

**Issue by michalstepien** [swiety85/angular2gridster#8]
Add ability change position (x,y) without reload grid.

**Comment by swiety85** [comment]
Done in version 0.4.0

**Comment by miloskovacevic** [comment]
After moving components to different positions on grid, and putting their x and y positions in console.log, positions are still the same. When i inspect the page, the components are in the same position like it was on the page load. Is there any way to see updated positions x and y of components after moving them around?

**Comment by swiety85** [comment]
Do you have to way binging on "[(x)]" and "[(y)]"? If yes, than this can be a bug in version 0.4.1. There is already a fix in v. 0.5.0.
Please use that version and give me a feedback if it works for you.

**Comment by miloskovacevic** [comment]
Thanks for prompt response! Currently using 0.5.0. Two-way communication doesn't work. Only works one-way, when i set initial position of components, but when i move them around the page and console.log the positions it shows starting positions.

**Comment by swiety85** [comment]
Hmm.. that's strange.. Can you have a look on demo app? Inside each gridster-item I displayed position and size - it is updating on each drag or resize action.
`                    Position: {{widget.x}} x {{widget.y}}
<br>
                    Size: {{widget.w}} x {{widget.h}}`
Do you use angular 2 or 4?
You can also try using events:
`<gridster-item [x]="item.x" (xChange)="itemChanged(item, $event)" [y]="item.y" (yChange)="itemChanged(item, $event)"></gridster-item>`

**Comment by miloskovacevic** [comment]
Hi! Sorry for late response. Tried both solutions, nothing happens. Tried with xChange and yChange like this 
![component](https://cloud.githubusercontent.com/assets/10956715/25121393/dbf0f492-2421-11e7-9ca9-37798f85adaa.png)
![function](https://cloud.githubusercontent.com/assets/10956715/25121397/e0f2759c-2421-11e7-92da-05fa329c91fa.png)

**Comment by miloskovacevic** [comment]
Tried 2-way binding with [(x)]="posXMain" and [(y)]="posYMain" , same results

**Comment by swiety85** [comment]
Can you make "itemChanged" method public and try again?

**Comment by miloskovacevic** [comment]
Just tried this, nothing happened. Thanks anyway! Really appreciate it!

**Comment by swiety85** [comment]
You were right. There was wrong build data. :-/
Please check it again with v. 0.5.1 and confirm if it works or not.
